--Creación de tablas
CREATE TABLE USUARIO(
IDUSUARIO INT PRIMARY KEY NOT NULL,
NOMBRE TEXT NOT NULL,
APELLIDOP TEXT NOT NULL,
APELLIDOM TEXT NOT NULL,
CORREO TEXT NOT NULL,
NUMERO INT NOT NULL);

CREATE TABLE CONTRASEÑA(
ID INT NOT NULL REFERENCES USUARIO(IDUSUARIO),
CONTRASEÑA TEXT NOT NULL);

--Inserts en USUARIO
INSERT INTO USUARIO (IDUSUARIO, NOMBRE, APELLIDOP, APELLIDOM, CORREO, NUMERO) 
VALUES (1, 'JUAN', 'PEREZ', 'PEREZ', 'JUAN@GMAIL.COM', 55555555);
INSERT INTO USUARIO (IDUSUARIO, NOMBRE, APELLIDOP, APELLIDOM, CORREO, NUMERO) 
VALUES (2, 'JOSE', 'ROBLES', 'ROBLES', 'JOSE@GMAIL.COM', 55555556);
INSERT INTO USUARIO (IDUSUARIO, NOMBRE, APELLIDOP, APELLIDOM, CORREO, NUMERO) 
VALUES (3, 'JULIO', 'ROMERO', 'ROBLES', 'JULIO@GMAIL.COM', 55555557);

--Inserts en CONTRASEÑA
INSERT INTO CONTRASEÑA (ID, CONTRASEÑA) VALUES (2, 'JOSEESLALEY');
INSERT INTO CONTRASEÑA (ID, CONTRASEÑA) VALUES (1, 'JUANESLALEY');
INSERT INTO CONTRASEÑA (ID, CONTRASEÑA) VALUES (3, 'JULIOESLALEY');