CREATE TABLE USUARIO(
IDUSUARIO INT PRIMARY KEY NOT NULL,
NOMBRE TEXT NOT NULL,
APELLIDOP TEXT NOT NULL,
APELLIDOM TEXT NOT NULL,
CORREO TEXT NOT NULL,
NUMERO INT NOT NULL);

CREATE TABLE CONTRASEÑA(
ID INT NOT NULL REFERENCES USUARIO(IDUSUARIO),
CONTRASEÑA TEXT NOT NULL);
